# -*- coding: utf-8 -*-

"""transform_houses_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxIKveZ7T_6ee_5YNBU6mbpj8c7pE6M2
"""

import pandas as pd
import os

# Create folders if not exist
os.makedirs("sources", exist_ok=True)

# Load raw data
df = pd.read_csv("sources/houses_in_milieuschutz.csv")

# Rename columns
column_mapping = {
    "adressid": "address_id",
    "hnr": "house_number",
    "hnr_zusatz": "house_number_extra",
    "str_name": "street_name",
    "plz": "postal_code",
    "code": "zone_code",
    "district": "neighborhood",
    "zone_name": "zone_name",
    "publication_date": "publication_date",
    "effective_date": "effective_date",
    "area_ha": "area_ha"
}
df = df.rename(columns=column_mapping)

# Keep only relevant columns
columns_to_keep = list(column_mapping.values())
df_cleaned = df[columns_to_keep]

# Convert datatypes
df_cleaned["address_id"] = df_cleaned["address_id"].astype(str)
df_cleaned["house_number"] = df_cleaned["house_number"].astype("Int64").astype(str)
df_cleaned["publication_date"] = pd.to_datetime(df_cleaned["publication_date"], errors="coerce")
df_cleaned["effective_date"] = pd.to_datetime(df_cleaned["effective_date"], errors="coerce")

# Save cleaned data
df_cleaned.to_csv("sources/cleaned_houses_in_zones.csv", index=False)

# Log summary
print("✅ Transformation complete.")
print(f"Rows: {len(df_cleaned)}")
print("Missing values per column:\n", df_cleaned.isna().sum())
