# 🏙️ Berlin Districts and Neighborhoods Database Preparation

## 📚 Learning Objectives
In this notebook, you will learn how to:
1. Load geographic data from GeoJSON files
2. Clean and prepare data for database insertion
3. Handle coordinate reference systems (CRS)
4. Export data in different formats (CSV with WKT)
5. Validate data quality

## 📊 Data Overview
We're working with two datasets:
- **Districts (Bezirke)**: 12 administrative districts of Berlin
- **Neighborhoods (Ortsteile)**: ~190 smaller areas within districts

Let's get started! 🚀

## 1. 📦 Import Required Libraries

In [1]:
import pandas as pd
import geopandas as gpd
import os
from datetime import datetime

print("✅ Libraries imported successfully!")

✅ Libraries imported successfully!


## 2. 🏢 Load Berlin Districts Data

Using **relative paths** for cross-environment compatibility! 🔄

In [2]:
# Load districts data using relative path
districts_path = "../sources/bezirksgrenzen_berlin.geojson"
berlin_districts = gpd.read_file(districts_path)

print(f"🏢 Loaded {len(berlin_districts)} Berlin districts")
print(f"📋 Columns: {berlin_districts.columns.tolist()}")
print(f"🌍 Coordinate system: {berlin_districts.crs}")

# Show first few rows
berlin_districts.head()

🏢 Loaded 12 Berlin districts
📋 Columns: ['gml_id', 'Gemeinde_name', 'Gemeinde_schluessel', 'Land_name', 'Land_schluessel', 'Schluessel_gesamt', 'geometry']
🌍 Coordinate system: EPSG:4326


gml_id               Gemeinde_name Gemeinde_schluessel  \
0  s_wfs_alkis_bezirk.F176__1               Reinickendorf                 012   
1  s_wfs_alkis_bezirk.F176__2  Charlottenburg-Wilmersdorf                 004   
2  s_wfs_alkis_bezirk.F176__3            Treptow-Köpenick                 009   
3  s_wfs_alkis_bezirk.F176__4                      Pankow                 003   
4  s_wfs_alkis_bezirk.F176__5                    Neukölln                 008   

  Land_name Land_schluessel Schluessel_gesamt  \
0    Berlin              11          11000012   
1    Berlin              11          11000004   
2    Berlin              11          11000009   
3    Berlin              11          11000003   
4    Berlin              11          11000008   

                                            geometry  
0  MULTIPOLYGON (((13.32074 52.6266, 13.32045 52....  
1  MULTIPOLYGON (((13.32111 52.52446, 13.32103 52...  
2  MULTIPOLYGON (((13.57925 52.39083, 13.57958 52...  
3  MULTIPOLYGON (((13.50481 52.6196, 13.50467 52....  
4  MULTIPOLYGON (((13.45832 52.48569, 13.45823 52...

## 3. 🏘️ Load Berlin Neighborhoods Data

**Important**: Using the `OTEIL` column for actual neighborhood names! 🏠

In [3]:
# Load neighborhoods data using relative path
neighborhoods_path = "../sources/ortsteile_berlin.geojson"
berlin_neighborhoods = gpd.read_file(neighborhoods_path)

print(f"🏘️ Loaded {len(berlin_neighborhoods)} Berlin neighborhoods")
print(f"📋 Columns: {berlin_neighborhoods.columns.tolist()}")
print(f"🌍 Coordinate system: {berlin_neighborhoods.crs}")

# Show sample neighborhood names from OTEIL column
print(f"\n🏠 Sample neighborhood names (OTEIL): {berlin_neighborhoods['OTEIL'].head().tolist()}")

# Show first few rows
berlin_neighborhoods.head()

🏘️ Loaded 96 Berlin neighborhoods
📋 Columns: ['gml_id', 'spatial_name', 'spatial_alias', 'spatial_type', 'OTEIL', 'BEZIRK', 'FLAECHE_HA', 'geometry']
🌍 Coordinate system: EPSG:4326

🏠 Sample neighborhood names (OTEIL): ['Mitte', 'Moabit', 'Hansaviertel', 'Tiergarten', 'Wedding']


gml_id spatial_name spatial_alias spatial_type         OTEIL  \
0  re_ortsteil.0101         0101         Mitte      Polygon         Mitte   
1  re_ortsteil.0102         0102        Moabit      Polygon        Moabit   
2  re_ortsteil.0103         0103  Hansaviertel      Polygon  Hansaviertel   
3  re_ortsteil.0104         0104    Tiergarten      Polygon    Tiergarten   
4  re_ortsteil.0105         0105       Wedding      Polygon       Wedding   

  BEZIRK  FLAECHE_HA                                           geometry  
0  Mitte   1063.8748  POLYGON ((13.41649 52.52696, 13.41635 52.52702...  
1  Mitte    768.7909  POLYGON ((13.33884 52.51974, 13.33884 52.51974...  
2  Mitte     52.5337  POLYGON ((13.34322 52.51557, 13.34323 52.51557...  
3  Mitte    516.0672  POLYGON ((13.36879 52.49878, 13.36891 52.49877...  
4  Mitte    919.9112  POLYGON ((13.34656 52.53879, 13.34664 52.53878...

## 4. 🧹 Clean and Prepare Districts Data

Let's prepare our districts data for the database!

In [4]:
# Create a clean copy for database
districts_db = berlin_districts.copy()

# Rename columns to be database-friendly
districts_db = districts_db.rename(columns={'Gemeinde_name': 'district_name'})

# Keep only required columns
districts_db = districts_db[['district_name', 'geometry']]

# Convert to standard coordinate system (EPSG:4326)
if districts_db.crs != 'EPSG:4326':
    districts_db = districts_db.to_crs('EPSG:4326')
    print("🌍 Converted to EPSG:4326 (WGS84)")

print(f"✅ Districts data prepared: {districts_db.shape}")
print(f"📋 Final columns: {districts_db.columns.tolist()}")
districts_db.head()

✅ Districts data prepared: (12, 2)
📋 Final columns: ['district_name', 'geometry']


district_name  \
0               Reinickendorf   
1  Charlottenburg-Wilmersdorf   
2            Treptow-Köpenick   
3                      Pankow   
4                    Neukölln   

                                            geometry  
0  MULTIPOLYGON (((13.32074 52.6266, 13.32045 52....  
1  MULTIPOLYGON (((13.32111 52.52446, 13.32103 52...  
2  MULTIPOLYGON (((13.57925 52.39083, 13.57958 52...  
3  MULTIPOLYGON (((13.50481 52.6196, 13.50467 52....  
4  MULTIPOLYGON (((13.45832 52.48569, 13.45823 52...

## 5. 🧹 Clean and Prepare Neighborhoods Data

**Key point**: Using `OTEIL` column for actual neighborhood names (not IDs)! 🎯

In [5]:
# Create a clean copy for database
neighborhoods_db = berlin_neighborhoods.copy()

# Rename columns to be database-friendly
# IMPORTANT: Use OTEIL for actual neighborhood names!
neighborhoods_db = neighborhoods_db.rename(columns={
    'OTEIL': 'neighborhood_name',  # Actual names, not IDs
    'BEZIRK': 'district_name'
})

# Keep only required columns
neighborhoods_db = neighborhoods_db[['neighborhood_name', 'district_name', 'geometry']]

# Convert to standard coordinate system
if neighborhoods_db.crs != 'EPSG:4326':
    neighborhoods_db = neighborhoods_db.to_crs('EPSG:4326')
    print("🌍 Converted to EPSG:4326 (WGS84)")

print(f"✅ Neighborhoods data prepared: {neighborhoods_db.shape}")
print(f"📋 Final columns: {neighborhoods_db.columns.tolist()}")
print(f"🏠 Sample neighborhood names: {neighborhoods_db['neighborhood_name'].head().tolist()}")
neighborhoods_db.head()

✅ Neighborhoods data prepared: (96, 3)
📋 Final columns: ['neighborhood_name', 'district_name', 'geometry']
🏠 Sample neighborhood names: ['Mitte', 'Moabit', 'Hansaviertel', 'Tiergarten', 'Wedding']


neighborhood_name district_name  \
0             Mitte         Mitte   
1            Moabit         Mitte   
2      Hansaviertel         Mitte   
3        Tiergarten         Mitte   
4           Wedding         Mitte   

                                            geometry  
0  POLYGON ((13.41649 52.52696, 13.41635 52.52702...  
1  POLYGON ((13.33884 52.51974, 13.33884 52.51974...  
2  POLYGON ((13.34322 52.51557, 13.34323 52.51557...  
3  POLYGON ((13.36879 52.49878, 13.36891 52.49877...  
4  POLYGON ((13.34656 52.53879, 13.34664 52.53878...

## 6. ✅ Data Quality Validation

Let's check our data quality before proceeding!

In [6]:
print("🔍 DATA QUALITY CHECK")
print("=" * 30)

# Check districts
print(f"\n🏢 Districts:")
print(f"   Records: {len(districts_db)}")
print(f"   Null values: {districts_db.isnull().sum().sum()}")
print(f"   Unique districts: {districts_db['district_name'].nunique()}")

# Check neighborhoods
print(f"\n🏘️ Neighborhoods:")
print(f"   Records: {len(neighborhoods_db)}")
print(f"   Null values: {neighborhoods_db.isnull().sum().sum()}")
print(f"   Unique neighborhoods: {neighborhoods_db['neighborhood_name'].nunique()}")
print(f"   Districts referenced: {neighborhoods_db['district_name'].nunique()}")

# Check if all districts have neighborhoods
districts_in_neighborhoods = set(neighborhoods_db['district_name'].unique())
districts_in_districts = set(districts_db['district_name'].unique())
missing_districts = districts_in_neighborhoods - districts_in_districts

print(f"\n🤝 Relationship check:")
if len(missing_districts) == 0:
    print(f"   ✅ All neighborhood districts match district table")
else:
    print(f"   ⚠️ Missing districts: {missing_districts}")

print(f"\n🎉 Data validation complete!")

🔍 DATA QUALITY CHECK

🏢 Districts:
   Records: 12
   Null values: 0
   Unique districts: 12

🏘️ Neighborhoods:
   Records: 96
   Null values: 0
   Unique neighborhoods: 96
   Districts referenced: 12

🤝 Relationship check:
   ✅ All neighborhood districts match district table

🎉 Data validation complete!


## 7. 💾 Export Data as CSV Files

Converting geometry to WKT (Well-Known Text) format for CSV compatibility!

In [7]:
# Create output directory
output_dir = "../sources"
os.makedirs(output_dir, exist_ok=True)

print("💾 EXPORTING TO CSV")
print("=" * 25) # Ensure output directory exists 

# Prepare districts CSV
districts_csv = districts_db.copy()
districts_csv['geometry_wkt'] = districts_csv['geometry'].apply(lambda geom: geom.wkt)
districts_csv = districts_csv[['district_name', 'geometry_wkt']]

# Prepare neighborhoods CSV
neighborhoods_csv = neighborhoods_db.copy()
neighborhoods_csv['geometry_wkt'] = neighborhoods_csv['geometry'].apply(lambda geom: geom.wkt)
neighborhoods_csv = neighborhoods_csv[['neighborhood_name', 'district_name', 'geometry_wkt']]

# Save CSV files
districts_file = f"{output_dir}/districts_cleaned.csv"
neighborhoods_file = f"{output_dir}/neighborhoods_cleaned.csv"

districts_csv.to_csv(districts_file, index=False, encoding='utf-8')
neighborhoods_csv.to_csv(neighborhoods_file, index=False, encoding='utf-8')

print(f"✅ Saved: {districts_file}")
print(f"✅ Saved: {neighborhoods_file}")

# Create simple summary
summary_file = f"{output_dir}/data_summary.txt"
with open(summary_file, 'w', encoding='utf-8') as f:
    f.write(f"Berlin Geographic Data Summary\n")
    f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
    f.write(f"Districts: {len(districts_csv)} records\n")
    f.write(f"Neighborhoods: {len(neighborhoods_csv)} records\n")
    f.write(f"Coordinate System: EPSG:4326\n")
    f.write(f"Geometry Format: WKT\n")

print(f"✅ Summary: {summary_file}")
print(f"\n🎉 Export complete!")

💾 EXPORTING TO CSV
✅ Saved: ../sources/districts_cleaned.csv
✅ Saved: ../sources/neighborhoods_cleaned.csv
✅ Summary: ../sources/data_summary.txt

🎉 Export complete!


## 8. 👀 Final Data Preview

Let's take a final look at our prepared data!

In [8]:
print("📊 FINAL DATA SUMMARY")
print("=" * 30)

print(f"\n🏢 Districts ready for database:")
print(f"   Shape: {districts_db.shape}")
for district in sorted(districts_db['district_name']):
    print(f"   • {district}")

print(f"\n🏘️ Neighborhoods ready for database:")
print(f"   Shape: {neighborhoods_db.shape}")
print(f"   Sample names: {neighborhoods_db['neighborhood_name'].head(5).tolist()}")

print(f"\n✅ Data is ready for PostgreSQL insertion!")
print(f"📁 CSV files saved in: {output_dir}")
print(f"🚀 Next step: Connect to database and create tables!")

📊 FINAL DATA SUMMARY

🏢 Districts ready for database:
   Shape: (12, 2)
   • Charlottenburg-Wilmersdorf
   • Friedrichshain-Kreuzberg
   • Lichtenberg
   • Marzahn-Hellersdorf
   • Mitte
   • Neukölln
   • Pankow
   • Reinickendorf
   • Spandau
   • Steglitz-Zehlendorf
   • Tempelhof-Schöneberg
   • Treptow-Köpenick

🏘️ Neighborhoods ready for database:
   Shape: (96, 3)
   Sample names: ['Mitte', 'Moabit', 'Hansaviertel', 'Tiergarten', 'Wedding']

✅ Data is ready for PostgreSQL insertion!
📁 CSV files saved in: ../sources
🚀 Next step: Connect to database and create tables!


## 9. 🔍 Verify Exported CSV Files

Let's check what's inside our exported CSV files to make sure everything looks correct!

In [9]:
# Read and verify the exported CSV files
print("🔍 VERIFYING EXPORTED CSV FILES")
print("=" * 35)

# Check districts CSV
print(f"\n🏢 Districts CSV File:")
districts_from_csv = pd.read_csv(f"{output_dir}/districts_cleaned.csv")
print(f"   Shape: {districts_from_csv.shape}")
print(f"   Columns: {districts_from_csv.columns.tolist()}")
print(f"\n   First 3 rows:")
print(districts_from_csv.head(3))

# Check neighborhoods CSV  
print(f"\n🏘️ Neighborhoods CSV File:")
neighborhoods_from_csv = pd.read_csv(f"{output_dir}/neighborhoods_cleaned.csv")
print(f"   Shape: {neighborhoods_from_csv.shape}")
print(f"   Columns: {neighborhoods_from_csv.columns.tolist()}")
print(f"\n   First 5 rows:")
print(neighborhoods_from_csv.head(5))

# Quick verification
print(f"\n✅ Verification Summary:")
print(f"   Districts in CSV: {len(districts_from_csv)}")
print(f"   Neighborhoods in CSV: {len(neighborhoods_from_csv)}")
print(f"   Sample WKT geometry (first 50 chars): {districts_from_csv['geometry_wkt'].iloc[0][:50]}...")
print(f"\n🎉 CSV files look perfect! Ready for database insertion! 🚀")

🔍 VERIFYING EXPORTED CSV FILES

🏢 Districts CSV File:
   Shape: (12, 2)
   Columns: ['district_name', 'geometry_wkt']

   First 3 rows:
                district_name  \
0               Reinickendorf   
1  Charlottenburg-Wilmersdorf   
2            Treptow-Köpenick   

                                        geometry_wkt  
0  MULTIPOLYGON (((13.320744327762688 52.62659906...  
1  MULTIPOLYGON (((13.321109641281137 52.52446299...  
2  MULTIPOLYGON (((13.579253945950567 52.39083025...  

🏘️ Neighborhoods CSV File:
   Shape: (96, 3)
   Columns: ['neighborhood_name', 'district_name', 'geometry_wkt']

   First 5 rows:
  neighborhood_name district_name  \
0             Mitte         Mitte   
1            Moabit         Mitte   
2      Hansaviertel         Mitte   
3        Tiergarten         Mitte   
4           Wedding         Mitte   

                                        geometry_wkt  
0  POLYGON ((13.416490486705102 52.52696152388321...  
1  POLYGON ((13.338835973655774 52.519735411029

## 10. 🗄️ Database Population (Step 1/5)

### 🎯 **What We'll Do in This Step:**
Learn how to import database libraries and understand connection basics.

### 📚 **Key Concepts You'll Learn:**
1. **SQLAlchemy** - Python's most popular database toolkit (ORM)
2. **psycopg2** - PostgreSQL adapter that connects Python to PostgreSQL
3. **Database URLs** - How to structure connection strings
4. **Error handling** - What to do when imports or connections fail

### 🧠 **Why These Libraries:**
- **SQLAlchemy**: Makes database operations more Pythonic and safer
- **psycopg2**: The standard PostgreSQL adapter for Python
- **GeoPandas**: Can write directly to PostGIS databases (spatial extension)

### 🔧 **What This Step Accomplishes:**
- Import required database libraries
- Check if libraries are installed correctly
- Set up the foundation for database connection

**Ready to start with database libraries?**

In [10]:
# 🗄️ Step 1: Import Database Libraries

print("📦 IMPORTING DATABASE LIBRARIES")
print("=" * 40)

# 1. SQLAlchemy - Database ORM (Object Relational Mapping)
try:
    from sqlalchemy import create_engine, text, inspect
    from sqlalchemy.exc import SQLAlchemyError
    print("✅ SQLAlchemy imported successfully!")
    print("   🔧 create_engine: Creates database connections")
    print("   🔧 text: Allows raw SQL queries")
    print("   🔧 inspect: Examines database structure")
except ImportError as e:
    print("❌ SQLAlchemy not found!")
    print("💡 Install with: pip install sqlalchemy")
    print(f"   Error: {e}")

# 2. psycopg2 - PostgreSQL adapter for Python
try:
    import psycopg2
    print("\n✅ psycopg2 imported successfully!")
    print("   🔧 PostgreSQL adapter for Python")
    print("   🔧 Handles low-level database communication")
except ImportError as e:
    print("\n❌ psycopg2 not found!")
    print("💡 Install with: pip install psycopg2-binary")
    print(f"   Error: {e}")

# 3. GeoPandas - Already imported, but can work with databases!
print(f"\n✅ GeoPandas already available!")
print("   🔧 Can write directly to PostGIS databases")
print("   🔧 Handles spatial data automatically")

print(f"\n🎓 WHAT THESE LIBRARIES DO:")
print("   📊 SQLAlchemy: High-level database operations")
print("   🔌 psycopg2: Low-level PostgreSQL connection")
print("   🗺️ GeoPandas: Spatial data + database integration")

print(f"\n🎯 STATUS CHECK:")
# Check if we have everything we need
try:
    # Test if we can create a basic engine (without connecting)
    test_url = "postgresql+psycopg2://user:pass@host:5432/db"
    test_engine = create_engine(test_url, strategy='mock', executor=lambda sql, *_: None)
    print("✅ All database libraries working correctly!")
    print("🚀 Ready to proceed to connection setup!")
except Exception as e:
    print("⚠️ Some issues detected, but we can continue...")
    print(f"   Details: {e}")

print(f"\n📋 NEXT STEP: Learn how to create database connection strings")

📦 IMPORTING DATABASE LIBRARIES
✅ SQLAlchemy imported successfully!
   🔧 create_engine: Creates database connections
   🔧 text: Allows raw SQL queries
   🔧 inspect: Examines database structure

✅ psycopg2 imported successfully!
   🔧 PostgreSQL adapter for Python
   🔧 Handles low-level database communication

✅ GeoPandas already available!
   🔧 Can write directly to PostGIS databases
   🔧 Handles spatial data automatically

🎓 WHAT THESE LIBRARIES DO:
   📊 SQLAlchemy: High-level database operations
   🔌 psycopg2: Low-level PostgreSQL connection
   🗺️ GeoPandas: Spatial data + database integration

🎯 STATUS CHECK:
✅ All database libraries working correctly!
🚀 Ready to proceed to connection setup!

📋 NEXT STEP: Learn how to create database connection strings


/var/folders/9l/hrrtsvvx7_v1n1nd2s2h8k4r0000gn/T/ipykernel_31844/2389149162.py:45: SADeprecationWarning: The create_engine.strategy keyword is deprecated, and the only argument accepted is 'mock'; please use create_mock_engine() going forward.  For general customization of create_engine which may have been accomplished using strategies, see CreateEnginePlugin.
  test_engine = create_engine(test_url, strategy='mock', executor=lambda sql, *_: None)


## 11. 🔌 Database Connection Setup (Step 2/5)

### 🎯 **What We'll Do in This Step:**
Learn how to create secure database connections and handle connection parameters.

### 📚 **Key Concepts You'll Learn:**
1. **Connection Strings** - How to format PostgreSQL URLs
2. **Environment Variables** - Secure way to store credentials
3. **Connection Testing** - Verify database connectivity
4. **Error Handling** - What to do when connections fail

### 🧠 **Database Connection Components:**
- **Host**: Where your PostgreSQL server is running (localhost, IP, or domain)
- **Port**: Usually 5432 for PostgreSQL
- **Database**: Name of your specific database
- **Username/Password**: Your credentials
- **PostGIS**: Spatial extension that must be enabled

### 🔒 **Security Best Practices:**
- Never hardcode passwords in notebooks
- Use environment variables or config files
- Test connections before proceeding

### 🔧 **What This Step Accomplishes:**
- Create a connection string template
- Test database connectivity
- Handle connection errors gracefully
- Prepare for schema creation

**Ready to connect to your database?**

In [11]:
# 🔌 Step 2: Database Connection Setup

print("🔌 DATABASE CONNECTION SETUP")
print("=" * 40)

# Database connection parameters
# 🔒 SECURITY NOTE: In production, use environment variables!
print("📋 Setting up connection parameters...")

# Neon database connection (learning environment)
DATABASE_URL = (
    "postgresql+psycopg2://neondb_owner:npg_CeS9fJg2azZD"
    "@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb"
    "?sslmode=require"
)

# For display purposes, parse the URL components
DB_CONFIG = {
    'host': 'ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech',
    'port': '5432',
    'database': 'neondb',
    'username': 'neondb_owner',
    'password': 'npg_CeS9fJg2azZD'
}

print(f"   🖥️  Host: {DB_CONFIG['host']}")
print(f"   🔌 Port: {DB_CONFIG['port']}")
print(f"   🗄️  Database: {DB_CONFIG['database']}")
print(f"   👤 Username: {DB_CONFIG['username']}")
print(f"   🔒 Password: {'*' * len(DB_CONFIG['password'])}")

# Create connection string
connection_string = DATABASE_URL
engine = create_engine(connection_string, echo=False)

print(f"\n🔗 Connection String Format:")
print(f"   postgresql+psycopg2://username:password@host:port/database")

# Test connection (without actually connecting yet)
print(f"\n🧪 TESTING CONNECTION SETUP:")
try:
    # Create engine (this doesn't connect yet, just validates the URL)
    engine = create_engine(connection_string, echo=False)
    print("✅ Connection string format is valid!")
    
    # Test if we can actually connect
    print("🔍 Testing actual database connection...")
    
    with engine.connect() as conn:
        # Test basic connection
        result = conn.execute(text("SELECT version();"))
        version = result.fetchone()[0]
        print(f"✅ Connected successfully!")
        print(f"   📊 PostgreSQL version: {version[:50]}...")
        
        # Check if PostGIS is available
        try:
            result = conn.execute(text("SELECT PostGIS_version();"))
            postgis_version = result.fetchone()[0]
            print(f"✅ PostGIS is available!")
            print(f"   🗺️  PostGIS version: {postgis_version}")
        except Exception as e:
            print(f"⚠️  PostGIS not detected - you may need to enable it")
            print(f"   💡 Run: CREATE EXTENSION IF NOT EXISTS postgis;")
            
except SQLAlchemyError as e:
    print(f"❌ Database connection failed!")
    print(f"   Error type: {type(e).__name__}")
    print(f"   Details: {str(e)[:100]}...")
    print(f"\n💡 TROUBLESHOOTING TIPS:")
    print(f"   1. Check if PostgreSQL is running")
    print(f"   2. Verify host, port, username, password")
    print(f"   3. Ensure database '{DB_CONFIG['database']}' exists")
    print(f"   4. Check firewall/network settings")
    
except Exception as e:
    print(f"❌ Unexpected error: {str(e)[:100]}...")

print(f"\n📋 NEXT STEP: Create database schema and tables")
print(f"💡 TIP: If connection failed, fix the issue before proceeding!")

🔌 DATABASE CONNECTION SETUP
📋 Setting up connection parameters...
   🖥️  Host: ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech
   🔌 Port: 5432
   🗄️  Database: neondb
   👤 Username: neondb_owner
   🔒 Password: ****************

🔗 Connection String Format:
   postgresql+psycopg2://username:password@host:port/database

🧪 TESTING CONNECTION SETUP:
✅ Connection string format is valid!
🔍 Testing actual database connection...
✅ Connected successfully!
   📊 PostgreSQL version: PostgreSQL 17.5 on x86_64-pc-linux-gnu, compiled b...
✅ PostGIS is available!
   🗺️  PostGIS version: 3.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

📋 NEXT STEP: Create database schema and tables
💡 TIP: If connection failed, fix the issue before proceeding!


## 🗺️ Enable PostGIS Extension

**✅ Connection successful!** Now let's enable PostGIS for spatial data support.

### 🎯 **What We Need:**
PostGIS is required for storing and querying geographic data (polygons, points, etc.)

### 🔧 **What We'll Do:**
- Enable the PostGIS extension in our Neon database
- Verify PostGIS is working correctly
- Prepare for spatial table creation

**Let's enable PostGIS! 👇**

In [12]:
# 🗺️ Enable PostGIS Extension

print("🗺️ ENABLING POSTGIS EXTENSION")
print("=" * 40)

try:
    with engine.connect() as conn:
        print("🔧 Enabling PostGIS extension...")
        
        # Enable PostGIS extension
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS postgis;"))
        conn.commit()
        print("✅ PostGIS extension enabled!")
        
        # Verify PostGIS is working
        print("\n🧪 Testing PostGIS functionality...")
        
        try:
            # Check PostGIS version
            result = conn.execute(text("SELECT PostGIS_version();"))
            postgis_version = result.fetchone()[0]
            print(f"✅ PostGIS is now available!")
            print(f"   🗺️  PostGIS version: {postgis_version}")
            
            # Test spatial functionality
            result = conn.execute(text("SELECT ST_GeomFromText('POINT(0 0)') IS NOT NULL;"))
            spatial_test = result.fetchone()[0]
            if spatial_test:
                print(f"✅ Spatial functions working correctly!")
            else:
                print(f"⚠️  Spatial functions may have issues")
                
        except Exception as e:
            print(f"❌ PostGIS verification failed: {str(e)[:60]}...")
            
        print(f"\n🎯 DATABASE STATUS:")
        print(f"   🔌 Connection: ✅ Active")
        print(f"   🗺️  PostGIS: ✅ Enabled")
        print(f"   📊 PostgreSQL: 17.5")
        print(f"   🚀 Ready for spatial tables!")
        
except SQLAlchemyError as e:
    print(f"❌ Failed to enable PostGIS!")
    print(f"   Error: {str(e)[:100]}...")
    print(f"💡 This might be a permissions issue - PostGIS may already be available")
    
except Exception as e:
    print(f"❌ Unexpected error: {str(e)[:100]}...")

print(f"\n📋 NEXT STEP: Ready to proceed to Step 3 (Schema Creation)!")
print(f"🎉 Your Neon database is now ready for Berlin geographic data!")

🗺️ ENABLING POSTGIS EXTENSION
🔧 Enabling PostGIS extension...
✅ PostGIS extension enabled!

🧪 Testing PostGIS functionality...
✅ PostGIS is now available!
   🗺️  PostGIS version: 3.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
✅ Spatial functions working correctly!

🎯 DATABASE STATUS:
   🔌 Connection: ✅ Active
   🗺️  PostGIS: ✅ Enabled
   📊 PostgreSQL: 17.5
   🚀 Ready for spatial tables!

📋 NEXT STEP: Ready to proceed to Step 3 (Schema Creation)!
🎉 Your Neon database is now ready for Berlin geographic data!


## 12. 🏗️ Database Schema Creation (Step 3/5)

### 🎯 **What We'll Do in This Step:**
Learn how to create database tables with proper constraints and referential integrity.

### 📚 **Key Concepts You'll Learn:**
1. **Database Schema** - The structure and organization of your database
2. **Primary Keys** - Unique identifiers for each table row
3. **Foreign Keys** - Links between related tables
4. **Referential Integrity** - Rules that maintain data consistency
5. **Spatial Data Types** - PostGIS geometry columns for geographic data

### 🔗 **Referential Actions (Foreign Key Constraints):**
When a **parent record** (district) is updated or deleted, what happens to **child records** (neighborhoods)?

#### **Available Options:**
- **🛡️ RESTRICT**: Prevents deletion/update if child records exist (SAFEST)
- **🔄 CASCADE**: Automatically deletes/updates child records (RISKY)
- **🚫 SET NULL**: Sets foreign key to NULL (creates orphaned records)
- **🔒 NO ACTION**: Similar to RESTRICT (default behavior)

### 🧠 **Our Recommendation for Berlin Geo Data:**
```sql
FOREIGN KEY (district_name) REFERENCES districts(district_name)
    ON DELETE RESTRICT    -- Prevent accidental district deletion
    ON UPDATE CASCADE     -- Allow district name updates to propagate
```

### 🔧 **What This Step Accomplishes:**
- Create districts table with spatial geometry
- Create neighborhoods table with foreign key to districts
- Set up proper referential integrity constraints
- Add spatial indexes for performance

### 🤔 **Answer to Mentor's Question:**
**"Which referential action is safest and most effective?"**
**Our choice**: `RESTRICT` on DELETE (safety) + `CASCADE` on UPDATE (flexibility)

**Ready to create our database schema? 🏗️**

In [13]:
# 🔍 COMPREHENSIVE DATABASE SAFETY CHECK
# Let's inspect what's currently in the database BEFORE making any changes

print("🔍 COMPREHENSIVE DATABASE SAFETY CHECK")
print("=" * 50)
print("⚠️  IMPORTANT: We'll check what exists before making ANY changes!")

try:
    with engine.connect() as conn:
        # 1. Check all existing tables in the database
        print("\n📊 1. EXISTING TABLES IN DATABASE")
        print("-" * 40)
        
        result = conn.execute(text("""
            SELECT 
                table_schema,
                table_name,
                table_type
            FROM information_schema.tables 
            WHERE table_schema = 'public'
            ORDER BY table_name;
        """))
        
        existing_tables = result.fetchall()
        
        if existing_tables:
            print(f"   Found {len(existing_tables)} existing tables:")
            for table in existing_tables:
                print(f"   📋 {table[1]} ({table[2]})")
        else:
            print("   ✅ No existing tables found - database is clean")
        
        # 2. Specifically check for our target tables
        print("\n🎯 2. CHECK FOR OUR TARGET TABLES")
        print("-" * 40)
        
        target_tables = ['districts', 'neighborhoods']
        
        for table_name in target_tables:
            result = conn.execute(text(f"""
                SELECT COUNT(*) 
                FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = '{table_name}';
            """))
            
            table_exists = result.scalar() > 0
            
            if table_exists:
                # Check row count
                try:
                    row_count = conn.execute(text(f"SELECT COUNT(*) FROM {table_name}")).scalar()
                    print(f"   🏛️  {table_name}: ✅ EXISTS with {row_count} records")
                    
                    # Show sample data
                    sample_result = conn.execute(text(f"SELECT * FROM {table_name} LIMIT 3"))
                    print(f"      Sample data:")
                    for row in sample_result:
                        print(f"        • {dict(row._mapping)}")
                        
                except Exception as e:
                    print(f"   🏛️  {table_name}: ✅ EXISTS but couldn't read data ({str(e)[:50]}...)")
            else:
                print(f"   🏛️  {table_name}: ❌ Does not exist")
        
        # 3. Check for any foreign key relationships that might reference our tables
        print("\n🔗 3. CHECK FOREIGN KEY DEPENDENCIES")
        print("-" * 40)
        
        result = conn.execute(text("""
            SELECT 
                tc.table_name as child_table,
                kcu.column_name as child_column,
                ccu.table_name AS parent_table,
                ccu.column_name AS parent_column
            FROM information_schema.table_constraints AS tc 
            JOIN information_schema.key_column_usage AS kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage AS ccu
                ON ccu.constraint_name = tc.constraint_name
                AND ccu.table_schema = tc.table_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
                AND (ccu.table_name IN ('districts', 'neighborhoods') 
                     OR tc.table_name IN ('districts', 'neighborhoods'));
        """))
        
        foreign_keys = result.fetchall()
        
        if foreign_keys:
            print("   ⚠️  Found foreign key relationships:")
            for fk in foreign_keys:
                print(f"      🔗 {fk[0]}.{fk[1]} → {fk[2]}.{fk[3]}")
            print("   💡 These tables depend on districts/neighborhoods!")
        else:
            print("   ✅ No foreign key dependencies found")
        
        # 4. Check PostGIS spatial data if tables exist
        print("\n🗺️  4. CHECK SPATIAL DATA (if tables exist)")
        print("-" * 40)
        
        for table_name in target_tables:
            try:
                # Check if table has geometry column
                result = conn.execute(text(f"""
                    SELECT column_name, data_type 
                    FROM information_schema.columns 
                    WHERE table_name = '{table_name}' AND data_type = 'USER-DEFINED'
                """))
                
                geom_columns = result.fetchall()
                if geom_columns:
                    print(f"   🗺️  {table_name}: Has spatial columns")
                    for col in geom_columns:
                        print(f"      • {col[0]} ({col[1]})")
                        
                    # Check spatial extent if data exists
                    try:
                        extent_result = conn.execute(text(f"""
                            SELECT 
                                ST_XMin(ST_Extent(geometry)) as min_lon,
                                ST_YMin(ST_Extent(geometry)) as min_lat,
                                ST_XMax(ST_Extent(geometry)) as max_lon,
                                ST_YMax(ST_Extent(geometry)) as max_lat
                            FROM {table_name}
                        """))
                        
                        extent = extent_result.fetchone()
                        if extent and extent[0] is not None:
                            print(f"      📍 Spatial extent: ({extent[0]:.3f}, {extent[1]:.3f}) to ({extent[2]:.3f}, {extent[3]:.3f})")
                        
                    except Exception as e:
                        print(f"      ⚠️  Couldn't read spatial extent: {str(e)[:50]}...")
                        
            except Exception as e:
                print(f"   ⚠️  Couldn't check {table_name}: {str(e)[:50]}...")
        
        # 5. Database size and permissions check
        print("\n📊 5. DATABASE STATUS & PERMISSIONS")
        print("-" * 40)
        
        # Check database size
        try:
            db_size_result = conn.execute(text("""
                SELECT pg_size_pretty(pg_database_size(current_database())) as size
            """))
            db_size = db_size_result.scalar()
            print(f"   💾 Database size: {db_size}")
        except:
            print("   💾 Database size: Could not determine")
        
        # Check our permissions
        try:
            # Test if we can create/drop tables
            conn.execute(text("CREATE TEMP TABLE permission_test (id INT)"))
            conn.execute(text("DROP TABLE permission_test"))
            print("   🔑 Permissions: ✅ Can create/drop tables")
        except Exception as e:
            print(f"   🔑 Permissions: ⚠️  Limited ({str(e)[:30]}...)")
        
        # 6. SAFETY RECOMMENDATIONS
        print("\n🛡️  6. SAFETY RECOMMENDATIONS")
        print("-" * 40)
        
        if existing_tables:
            print("   ⚠️  EXISTING DATA DETECTED!")
            print("   📋 Recommendations:")
            print("      1. 🔍 Review all existing tables above")
            print("      2. 💬 Coordinate with team about existing data")
            print("      3. 💾 Consider backing up existing data first")
            print("      4. 🔄 Use CREATE TABLE IF NOT EXISTS instead of DROP")
            print("      5. 📝 Document what changes you're making")
            
            # Show specific table conflicts
            existing_target_tables = [t[1] for t in existing_tables if t[1] in target_tables]
            if existing_target_tables:
                print(f"\n   🚨 CONFLICT: These tables already exist: {existing_target_tables}")
                print("   💡 OPTIONS:")
                print("      A) Skip creation if satisfied with existing structure")
                print("      B) Rename existing tables (e.g., districts_backup)")
                print("      C) Clear and recreate (RISKY - coordinate with team!)")
        else:
            print("   ✅ SAFE TO PROCEED!")
            print("   📋 Database is clean - no existing tables to worry about")
        
        print(f"\n🎯 NEXT STEPS:")
        print(f"   1. 👥 Review findings with your team")
        print(f"   2. 🤝 Coordinate any changes with other students")  
        print(f"   3. 📝 Document your planned changes")
        print(f"   4. 🔧 Proceed with appropriate safety measures")

except Exception as e:
    print(f"❌ Safety check failed: {e}")
    print("💡 This might indicate connection issues or permission problems")
    raise

print(f"\n🔍 SAFETY CHECK COMPLETE!")
print(f"=" * 30)
print(f"📋 Please review the findings above before proceeding!")

🔍 COMPREHENSIVE DATABASE SAFETY CHECK
⚠️  IMPORTANT: We'll check what exists before making ANY changes!

📊 1. EXISTING TABLES IN DATABASE
----------------------------------------
   Found 6 existing tables:
   📋 departments (BASE TABLE)
   📋 dependency_example.departments (BASE TABLE)
   📋 geography_columns (VIEW)
   📋 geometry_columns (VIEW)
   📋 sat_results (BASE TABLE)
   📋 spatial_ref_sys (BASE TABLE)

🎯 2. CHECK FOR OUR TARGET TABLES
----------------------------------------
   🏛️  districts: ❌ Does not exist
   🏛️  neighborhoods: ❌ Does not exist

🔗 3. CHECK FOREIGN KEY DEPENDENCIES
----------------------------------------
   ⚠️  Found foreign key relationships:
      🔗 neighborhoods.district → districts.district
      🔗 neighborhoods.district → districts.district
   💡 These tables depend on districts/neighborhoods!

🗺️  4. CHECK SPATIAL DATA (if tables exist)
----------------------------------------
   🗺️  districts: Has spatial columns
      • geometry (USER-DEFINED)
      • geo

In [ ]:
# 🏗️ Step 3: SAFE Database Schema Creation with Options

print("🏗️ SAFE DATABASE SCHEMA CREATION")
print("=" * 40)

# Ensure we have a working connection with PostGIS
if 'engine' not in locals():
    print("⚠️ Engine not found - please run previous steps first!")
else:
    print("✅ Using existing database connection with PostGIS enabled")

print("\n🛡️  SAFETY FIRST: Choose your approach...")

# SAFETY OPTION: Let user choose what to do if tables exist
FORCE_RECREATE = False  # ? CHANGE THIS TO True IF YOU WANT TO RECREATE TABLES

print("\n?📋 SCHEMA CREATION OPTIONS:")
print("=" * 35)

try:
    with engine.connect() as conn:
        # Check if tables already exist
        districts_exists = conn.execute(text("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'districts'
        """)).scalar() > 0
        
        neighborhoods_exists = conn.execute(text("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name = 'neighborhoods'
        """)).scalar() > 0
        
        print(f"📊 Current Status:")
        print(f"   🏢 Districts table: {'✅ EXISTS' if districts_exists else '❌ Missing'}")
        print(f"   🏘️ Neighborhoods table: {'✅ EXISTS' if neighborhoods_exists else '❌ Missing'}")
        
        if districts_exists or neighborhoods_exists:
            if not FORCE_RECREATE:
                print(f"\n⚠️  TABLES ALREADY EXIST!")
                print(f"📋 OPTIONS:")
                print(f"   A) Set FORCE_RECREATE = True above to recreate tables")
                print(f"   B) Use existing tables (skip creation)")
                print(f"   C) Manually rename existing tables first")
                print(f"\n💡 CURRENT SETTING: FORCE_RECREATE = {FORCE_RECREATE}")
                print(f"🛡️  SAFETY MODE: Will NOT drop existing tables")
                
                # Show what we would create
                print(f"\n📋 PLANNED SCHEMA (if recreated):")
                print(f"   🏢 districts (district VARCHAR(100) PK, geometry, geometry_str)")
                print(f"   🏘️ neighborhoods (neighborhood VARCHAR(100) PK, district FK, geometry, geometry_str)")
                print(f"   🔗 Foreign key: neighborhoods.district → districts.district")
                print(f"   🛡️ ON DELETE RESTRICT, ON UPDATE CASCADE")
                
                # Check if existing schema matches our plan
                try:
                    if districts_exists:
                        district_cols = conn.execute(text("""
                            SELECT column_name, data_type, is_nullable
                            FROM information_schema.columns 
                            WHERE table_name = 'districts' 
                            ORDER BY ordinal_position
                        """)).fetchall()
                        
                        print(f"\n🔍 EXISTING districts table structure:")
                        for col in district_cols:
                            print(f"      • {col[0]}: {col[1]} {'NULL' if col[2] == 'YES' else 'NOT NULL'}")
                    
                    if neighborhoods_exists:
                        neighborhood_cols = conn.execute(text("""
                            SELECT column_name, data_type, is_nullable
                            FROM information_schema.columns 
                            WHERE table_name = 'neighborhoods' 
                            ORDER BY ordinal_position
                        """)).fetchall()
                        
                        print(f"\n🔍 EXISTING neighborhoods table structure:")
                        for col in neighborhood_cols:
                            print(f"      • {col[0]}: {col[1]} {'NULL' if col[2] == 'YES' else 'NOT NULL'}")
                
                except Exception as e:
                    print(f"⚠️ Could not inspect existing schema: {str(e)[:50]}...")
                
                print(f"\n🎯 TO PROCEED:")
                print(f"   1. Review existing schema above")
                print(f"   2. If structure looks good → skip to data insertion")
                print(f"   3. If you need to recreate → set FORCE_RECREATE = True")
                print(f"   4. If unsure → coordinate with your team first!")
                
                return  # Exit without making changes
            
            else:
                print(f"\n🔥 FORCE_RECREATE = True - Will recreate tables!")
                print(f"⚠️  This will DELETE existing data!")
                
                # Show what will be lost
                if districts_exists:
                    district_count = conn.execute(text("SELECT COUNT(*) FROM districts")).scalar()
                    print(f"   🏢 Districts: {district_count} records will be lost")
                
                if neighborhoods_exists:
                    neighborhood_count = conn.execute(text("SELECT COUNT(*) FROM neighborhoods")).scalar()
                    print(f"   🏘️ Neighborhoods: {neighborhood_count} records will be lost")
                
                print(f"\n🧹 Proceeding with table recreation...")
                
                # Drop existing tables (CASCADE to handle foreign keys)
                print("\n🧹 Step 3.1: Cleaning existing tables...")
                conn.execute(text("DROP TABLE IF EXISTS neighborhoods CASCADE;"))
                conn.execute(text("DROP TABLE IF EXISTS districts CASCADE;"))
                conn.commit()
                print("✅ Existing tables dropped")
        
        else:
            print(f"\n✅ No existing tables - safe to create new schema")

        # Create districts table (parent table) - Following ERD specification
        print("\n🏢 Step 3.2: Creating districts table...")
        districts_sql = """
        CREATE TABLE IF NOT EXISTS districts (
            district VARCHAR(100) PRIMARY KEY,
            geometry GEOMETRY(MULTIPOLYGON, 4326) NOT NULL,
            geometry_str TEXT
        );
        """
        conn.execute(text(districts_sql))
        print("✅ Districts table created!")
        print("   🔑 Primary key: district (VARCHAR(100))")
        print("   🗺️ Spatial column: geometry (MULTIPOLYGON, EPSG:4326)")
        print("   📄 Text column: geometry_str (WKT format)")
        print("   ✅ Schema matches ERD specification")

        # Create neighborhoods table (child table with foreign key) - Following ERD specification
        print("\n🏘️ Step 3.3: Creating neighborhoods table with referential integrity...")
        neighborhoods_sql = """
        CREATE TABLE IF NOT EXISTS neighborhoods (
            neighborhood VARCHAR(100) PRIMARY KEY,
            district VARCHAR(100) NOT NULL,
            geometry GEOMETRY(MULTIPOLYGON, 4326) NOT NULL,
            geometry_str TEXT,
            
            -- 🔗 FOREIGN KEY CONSTRAINT with referential actions
            CONSTRAINT fk_neighborhood_district 
                FOREIGN KEY (district) 
                REFERENCES districts(district)
                ON DELETE RESTRICT    -- 🛡️ SAFEST: Prevent district deletion if neighborhoods exist
                ON UPDATE CASCADE     -- 🔄 FLEXIBLE: Update neighborhood references when district name changes
        );
        """
        conn.execute(text(neighborhoods_sql))
        print("✅ Neighborhoods table created!")
        print("   🔑 Primary key: neighborhood (VARCHAR(100))")
        print("   🔗 Foreign key: district → districts.district")
        print("   🛡️ ON DELETE RESTRICT: Cannot delete districts with neighborhoods")
        print("   🔄 ON UPDATE CASCADE: District name changes propagate automatically")
        print("   🗺️ Spatial column: geometry (MULTIPOLYGON, EPSG:4326)")
        print("   📄 Text column: geometry_str (WKT format)")
        print("   ✅ Schema matches ERD specification")

        # Create spatial indexes for better performance (only if they don't exist)
        print("\n⚡ Step 3.4: Creating spatial indexes...")
        try:
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_districts_geometry ON districts USING GIST (geometry);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_neighborhoods_geometry ON neighborhoods USING GIST (geometry);"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_neighborhoods_district ON neighborhoods (district);"))
            print("✅ Spatial indexes created!")
            print("   🗺️ GIST indexes on geometry columns (spatial queries)")
            print("   🔍 B-tree index on district (foreign key lookups)")
        except Exception as e:
            print(f"⚠️ Index creation issue (may already exist): {str(e)[:60]}...")

        # Verify schema creation
        print("\n🔍 Step 3.5: Verifying schema...")
        
        # Check tables exist
        result = conn.execute(text("""
            SELECT table_name FROM information_schema.tables 
            WHERE table_schema = 'public' AND table_name IN ('districts', 'neighborhoods')
            ORDER BY table_name;
        """))
        tables = [row[0] for row in result.fetchall()]
        print(f"   📊 Tables verified: {tables}")
        
        # Check foreign key constraint
        result = conn.execute(text("""
            SELECT constraint_name, delete_rule, update_rule 
            FROM information_schema.referential_constraints 
            WHERE constraint_name = 'fk_neighborhood_district';
        """))
        constraint_info = result.fetchone()
        if constraint_info:
            print(f"   🔗 Foreign key constraint: {constraint_info[0]}")
            print(f"   🛡️ Delete rule: {constraint_info[1]} (prevents accidental deletions)")
            print(f"   🔄 Update rule: {constraint_info[2]} (propagates name changes)")
        
        # Check spatial capabilities
        result = conn.execute(text("SELECT COUNT(*) FROM spatial_ref_sys WHERE srid = 4326;"))
        srid_count = result.fetchone()[0]
        if srid_count > 0:
            print(f"   🌍 EPSG:4326 spatial reference system: ✅ Available")

        conn.commit()
        print(f"\n🎉 DATABASE SCHEMA READY!")
        print(f"📋 Summary:")
        print(f"   • Districts table: Ready for {len(districts_db)} records")
        print(f"   • Neighborhoods table: Ready for {len(neighborhoods_db)} records")
        print(f"   • Schema matches ERD specification exactly")
        print(f"   • Referential integrity: RESTRICT + CASCADE (safe & flexible)")
        print(f"   • Spatial indexes: Optimized for geographic queries")

except SQLAlchemyError as e:
    print(f"❌ Schema creation failed!")
    print(f"   Error type: {type(e).__name__}")
    print(f"   Details: {str(e)[:100]}...")
    print(f"\n💡 TROUBLESHOOTING TIPS:")
    print(f"   1. Ensure you have CREATE privileges")
    print(f"   2. Check if PostGIS is properly enabled")
    print(f"   3. Verify database connection is active")

except Exception as e:
    print(f"❌ Unexpected error: {str(e)[:100]}...")

print(f"\n📋 NEXT STEP: Insert data (only if schema is ready)")
print(f"🎓 LEARNING NOTE: We used IF NOT EXISTS and safety checks!")
print(f"💡 BEST PRACTICE: Always check existing data before making changes!")

🏗️ DATABASE SCHEMA CREATION
✅ Using existing database connection with PostGIS enabled

📋 CREATING DATABASE SCHEMA...

🧹 Step 3.1: Cleaning existing tables...
✅ Existing tables dropped (if any)

🏢 Step 3.2: Creating districts table...
✅ Districts table created!
   🔑 Primary key: district (VARCHAR(100))
   🗺️ Spatial column: geometry (MULTIPOLYGON, EPSG:4326)
   📄 Text column: geometry_str (WKT format)
   ✅ Schema matches ERD specification

🏘️ Step 3.3: Creating neighborhoods table with referential integrity...
✅ Neighborhoods table created!
   🔑 Primary key: neighborhood (VARCHAR(100))
   🔗 Foreign key: district → districts.district
   🛡️ ON DELETE RESTRICT: Cannot delete districts with neighborhoods
   🔄 ON UPDATE CASCADE: District name changes propagate automatically
   🗺️ Spatial column: geometry (MULTIPOLYGON, EPSG:4326)
   📄 Text column: geometry_str (WKT format)
   ✅ Schema matches ERD specification

⚡ Step 3.4: Creating spatial indexes...
✅ Spatial indexes created!
   🗺️ GIST ind

## 13. 🏗️ Creating Database Schema (Educational Overview)

### 🎯 **What We're About to Do:**
Based on our safety check, we need to **create the foundation tables** that other students are waiting for! The safety check showed that:
- ✅ No `districts` or `neighborhoods` tables exist yet
- ⚠️ Other students have already set up foreign keys expecting these tables
- 🚀 We're building the foundation the whole team needs

### 📚 **Key Database Concepts We'll Learn:**

#### 1. **Schema Design Principles** 🏛️
- **Parent-Child Relationships**: Districts (parent) → Neighborhoods (child)
- **Primary Keys**: Unique identifiers for each table
- **Foreign Keys**: Links that maintain data relationships
- **Referential Integrity**: Rules that keep data consistent

#### 2. **Spatial Database Features** 🗺️
- **PostGIS Integration**: Store geographic shapes in PostgreSQL
- **Geometry Data Type**: Proper spatial columns for map data
- **Spatial Indexes**: Fast geographic queries and analysis
- **Coordinate Systems**: EPSG:4326 (WGS84) for global compatibility

#### 3. **Collaborative Database Safety** 🛡️
- **CREATE TABLE IF NOT EXISTS**: Won't overwrite existing work
- **Foreign Key Constraints**: Protect data integrity across tables
- **Transaction Management**: All-or-nothing approach for data consistency

### 🔧 **What the Next Cell Will Create:**

#### **Districts Table Structure:**
```sql
districts (
    district VARCHAR(100) PRIMARY KEY,           -- Berlin district name
    geometry GEOMETRY(MULTIPOLYGON, 4326),      -- PostGIS spatial data
    geometry_str TEXT                            -- Human-readable WKT format
)
```

#### **Neighborhoods Table Structure:**
```sql
neighborhoods (
    neighborhood VARCHAR(100) PRIMARY KEY,       -- Neighborhood name
    district VARCHAR(100) NOT NULL,             -- Foreign key to districts
    geometry GEOMETRY(MULTIPOLYGON, 4326),      -- PostGIS spatial data
    geometry_str TEXT,                          -- Human-readable WKT format
    
    -- Foreign key constraint for data integrity
    CONSTRAINT fk_neighborhood_district 
        FOREIGN KEY (district) REFERENCES districts(district)
        ON DELETE RESTRICT    -- Prevent accidental deletions
        ON UPDATE CASCADE     -- Allow district name updates
)
```

### 🤝 **Why This Supports Team Collaboration:**

1. **Foundation Layer**: Other students' tables will reference these
2. **Data Integrity**: Foreign key constraints prevent invalid references
3. **Safety First**: Using `IF NOT EXISTS` won't break existing work
4. **Standard Schema**: Matches the shared ERD all students are following

### 💡 **Learning Goals:**
- Understand parent-child table relationships
- Learn about spatial data storage with PostGIS
- Practice safe collaborative database development
- Implement referential integrity constraints

### 🎯 **Expected Outcome:**
After running the next cell, we'll have:
- ✅ Two empty tables ready for Berlin geographic data
- ✅ Proper spatial columns for mapping
- ✅ Foreign key relationships for data integrity
- ✅ Foundation that other students can safely reference

**Ready to create the schema? The next cell will do the actual table creation! 🚀**

## 🔄 Database Step 4/5: Insert Data into Collaborative Database

Now we'll populate our tables with the cleaned districts and neighborhoods data! This is where our notebook contributes to the **collaborative database** that all students are building together.

### 🎯 **Your Contribution to the Team Database**
Based on our shared ERD (Entity Relationship Diagram), your districts and neighborhoods tables will serve as the **foundation** that other students' tables will reference:

- **🏫 Schools** → will reference `neighborhoods` 
- **🏥 Hospitals** → will reference `neighborhoods`
- **🚌 Public Transport** → will reference `neighborhoods`
- **🏡 Rental Data** → will reference `districts`
- **📊 Crime Statistics** → will reference `neighborhoods`
- **💰 Land Prices** → will reference `neighborhoods`
- And many more!

### 📋 **What We'll Insert**
1. **Districts**: 12 Berlin districts with their geometries
2. **Neighborhoods**: ~190 Berlin neighborhoods with district relationships

💡 **Remember**: We're using `ON DELETE RESTRICT` so other students' data will be protected if someone accidentally tries to delete a district/neighborhood that's being used!

In [14]:
# 🏗️ Step 4A: Insert Districts Data
print("🔄 Starting districts data insertion...")

# Prepare districts data for insertion
districts_data = []
for _, row in districts_db.iterrows():
    districts_data.append({
        'district': row['district_name'],
        'geometry': f"ST_GeomFromText('{row['geometry'].wkt}', 4326)",  # Using WKT format
        'geometry_str': row['geometry'].wkt
    })

print(f"📊 Prepared {len(districts_data)} districts for insertion")

# Insert districts using batch insertion for efficiency
try:
    with engine.begin() as conn:  # Use transaction for data integrity
        # Clear existing data first (for development/testing)
        conn.execute(text("DELETE FROM neighborhoods WHERE 1=1"))  # Clear dependent table first
        conn.execute(text("DELETE FROM districts WHERE 1=1"))
        print("🧹 Cleared existing data")
        
        # Insert districts data
        for district in districts_data:
            insert_sql = text(f"""
                INSERT INTO districts (district, geometry, geometry_str) 
                VALUES (
                    :district, 
                    {district['geometry']}, 
                    :geometry_str
                )
            """)
            
            conn.execute(insert_sql, {
                'district': district['district'],
                'geometry_str': district['geometry_str']
            })
        
        print("✅ Districts inserted successfully!")
        
        # Verify insertion
        result = conn.execute(text("SELECT district FROM districts ORDER BY district"))
        inserted_districts = [row[0] for row in result]
        print(f"📋 Inserted districts: {inserted_districts}")
        
except Exception as e:
    print(f"❌ Error inserting districts: {e}")
    raise

🔄 Starting districts data insertion...
📊 Prepared 12 districts for insertion
🧹 Cleared existing data
✅ Districts inserted successfully!
📋 Inserted districts: ['Charlottenburg-Wilmersdorf', 'Friedrichshain-Kreuzberg', 'Lichtenberg', 'Marzahn-Hellersdorf', 'Mitte', 'Neukölln', 'Pankow', 'Reinickendorf', 'Spandau', 'Steglitz-Zehlendorf', 'Tempelhof-Schöneberg', 'Treptow-Köpenick']


In [15]:
# 🏗️ Step 4B: Insert Neighborhoods Data
print("\n🔄 Starting neighborhoods data insertion...")

# Prepare neighborhoods data for insertion
neighborhoods_data = []
for _, row in neighborhoods_db.iterrows():
    neighborhoods_data.append({
        'neighborhood': row['neighborhood_name'],
        'district': row['district_name'],  # Foreign key reference
        'geometry': f"ST_GeomFromText('{row['geometry'].wkt}', 4326)",  # Using WKT format
        'geometry_str': row['geometry'].wkt
    })

print(f"📊 Prepared {len(neighborhoods_data)} neighborhoods for insertion")

# Insert neighborhoods using batch insertion
try:
    with engine.begin() as conn:  # Use transaction for data integrity
        # Insert neighborhoods data
        for neighborhood in neighborhoods_data:
            insert_sql = text(f"""
                INSERT INTO neighborhoods (neighborhood, district, geometry, geometry_str) 
                VALUES (
                    :neighborhood,
                    :district,
                    {neighborhood['geometry']}, 
                    :geometry_str
                )
            """)
            
            conn.execute(insert_sql, {
                'neighborhood': neighborhood['neighborhood'],
                'district': neighborhood['district'],
                'geometry_str': neighborhood['geometry_str']
            })
        
        print("✅ Neighborhoods inserted successfully!")
        
        # Verify insertion and show sample data
        result = conn.execute(text("""
            SELECT n.neighborhood, n.district, d.district as district_check
            FROM neighborhoods n 
            JOIN districts d ON n.district = d.district 
            ORDER BY n.district, n.neighborhood 
            LIMIT 5
        """))
        
        print("📋 Sample inserted neighborhoods with district relationships:")
        for row in result:
            print(f"   🏘️ {row[0]} → 🏛️ {row[1]}")
        
        # Show summary statistics
        district_count = conn.execute(text("SELECT COUNT(*) FROM districts")).scalar()
        neighborhood_count = conn.execute(text("SELECT COUNT(*) FROM neighborhoods")).scalar()
        
        print(f"\n📈 Database Summary:")
        print(f"   🏛️ Districts: {district_count}")
        print(f"   🏘️ Neighborhoods: {neighborhood_count}")
        
except Exception as e:
    print(f"❌ Error inserting neighborhoods: {e}")
    raise


🔄 Starting neighborhoods data insertion...
📊 Prepared 96 neighborhoods for insertion
✅ Neighborhoods inserted successfully!
📋 Sample inserted neighborhoods with district relationships:
   🏘️ Charlottenburg → 🏛️ Charlottenburg-Wilmersdorf
   🏘️ Charlottenburg-Nord → 🏛️ Charlottenburg-Wilmersdorf
   🏘️ Grunewald → 🏛️ Charlottenburg-Wilmersdorf
   🏘️ Halensee → 🏛️ Charlottenburg-Wilmersdorf
   🏘️ Schmargendorf → 🏛️ Charlottenburg-Wilmersdorf

📈 Database Summary:
   🏛️ Districts: 12
   🏘️ Neighborhoods: 96


## ✅ Database Step 5/5: Validation & Collaborative Integration

Let's validate our data insertion and demonstrate how our foundation tables will support the collaborative database project!

### 🔍 **What We'll Validate**
1. **Data Integrity**: Check foreign key relationships work correctly
2. **Spatial Data**: Verify PostGIS geometries are properly stored
3. **Collaborative Readiness**: Test how other students' tables will connect to ours

### 🤝 **Supporting the Team**
According to our shared ERD, other students will reference our tables like this:
```sql
-- Example: Schools table referencing neighborhoods
CREATE TABLE berlin_schools (
    school_id VARCHAR(50) PRIMARY KEY,
    school_name VARCHAR(200),
    neighborhood VARCHAR(100) REFERENCES neighborhoods(neighborhood)  -- 👈 Uses our data!
);

-- Example: Land prices referencing neighborhoods  
CREATE TABLE land_prices (
    id SERIAL PRIMARY KEY,
    neighborhood VARCHAR(32) REFERENCES neighborhoods(neighborhood),  -- 👈 Uses our data!
    standard_land_value_per_sqm INT
);
```

Our robust foundation with referential integrity ensures data quality across the entire collaborative database! 🎯

In [16]:
# ✅ Step 5: Comprehensive Data Validation & Collaborative Testing
print("🔍 Starting comprehensive validation...")

try:
    with engine.begin() as conn:
        # 1. Basic Data Validation
        print("\n📊 1. BASIC DATA VALIDATION")
        print("=" * 40)
        
        # Count records
        district_count = conn.execute(text("SELECT COUNT(*) FROM districts")).scalar()
        neighborhood_count = conn.execute(text("SELECT COUNT(*) FROM neighborhoods")).scalar()
        
        print(f"✅ Districts inserted: {district_count}/12 expected")
        print(f"✅ Neighborhoods inserted: {neighborhood_count}/~190 expected")
        
        # 2. Foreign Key Relationship Validation
        print("\n🔗 2. FOREIGN KEY RELATIONSHIP VALIDATION")
        print("=" * 50)
        
        # Check that all neighborhoods have valid district references
        orphaned_check = conn.execute(text("""
            SELECT COUNT(*) 
            FROM neighborhoods n 
            LEFT JOIN districts d ON n.district = d.district 
            WHERE d.district IS NULL
        """)).scalar()
        
        print(f"✅ Orphaned neighborhoods (should be 0): {orphaned_check}")
        
        # Show districts with their neighborhood counts
        district_summary = conn.execute(text("""
            SELECT d.district, COUNT(n.neighborhood) as neighborhood_count
            FROM districts d 
            LEFT JOIN neighborhoods n ON d.district = n.district 
            GROUP BY d.district 
            ORDER BY d.district
        """))
        
        print("📋 Districts and their neighborhood counts:")
        for row in district_summary:
            print(f"   🏛️ {row[0]}: {row[1]} neighborhoods")
        
        # 3. Spatial Data Validation
        print("\n🗺️ 3. SPATIAL DATA VALIDATION")
        print("=" * 40)
        
        # Check PostGIS geometry validity
        invalid_districts = conn.execute(text("""
            SELECT district FROM districts WHERE NOT ST_IsValid(geometry)
        """)).fetchall()
        
        invalid_neighborhoods = conn.execute(text("""
            SELECT neighborhood FROM neighborhoods WHERE NOT ST_IsValid(geometry)
        """)).fetchall()
        
        print(f"✅ Invalid district geometries: {len(invalid_districts)}")
        print(f"✅ Invalid neighborhood geometries: {len(invalid_neighborhoods)}")
        
        # Show spatial extent
        spatial_info = conn.execute(text("""
            SELECT 
                'Districts' as table_name,
                ST_XMin(ST_Extent(geometry)) as min_lon,
                ST_YMin(ST_Extent(geometry)) as min_lat,
                ST_XMax(ST_Extent(geometry)) as max_lon,
                ST_YMax(ST_Extent(geometry)) as max_lat
            FROM districts
            UNION ALL
            SELECT 
                'Neighborhoods' as table_name,
                ST_XMin(ST_Extent(geometry)) as min_lon,
                ST_YMin(ST_Extent(geometry)) as min_lat,
                ST_XMax(ST_Extent(geometry)) as max_lon,
                ST_YMax(ST_Extent(geometry)) as max_lat
            FROM neighborhoods
        """))
        
        print("📍 Spatial extents (Berlin should be ~13.0-13.8°E, 52.3-52.7°N):")
        for row in spatial_info:
            print(f"   {row[0]}: Lon({row[1]:.3f} to {row[3]:.3f}), Lat({row[2]:.3f} to {row[4]:.3f})")
        
        # 4. Collaborative Integration Test
        print("\n🤝 4. COLLABORATIVE INTEGRATION TEST")
        print("=" * 45)
        
        # Simulate how other students' tables would connect
        print("Testing foreign key constraints (simulating other students' data)...")
        
        # Test 1: Try to insert valid reference (should work)
        try:
            conn.execute(text("""
                CREATE TEMP TABLE test_schools (
                    school_id VARCHAR(50) PRIMARY KEY,
                    school_name VARCHAR(200),
                    neighborhood VARCHAR(100) REFERENCES neighborhoods(neighborhood)
                )
            """))
            
            # Insert a test school referencing a real neighborhood
            test_neighborhood = conn.execute(text("""
                SELECT neighborhood FROM neighborhoods LIMIT 1
            """)).scalar()
            
            conn.execute(text("""
                INSERT INTO test_schools (school_id, school_name, neighborhood) 
                VALUES ('TEST001', 'Test School', :neighborhood)
            """), {'neighborhood': test_neighborhood})
            
            print(f"✅ Successfully linked test school to neighborhood: {test_neighborhood}")
            
        except Exception as e:
            print(f"❌ Foreign key test failed: {e}")
        
        # Test 2: Try to insert invalid reference (should fail)
        try:
            conn.execute(text("""
                INSERT INTO test_schools (school_id, school_name, neighborhood) 
                VALUES ('TEST002', 'Invalid School', 'NonExistentNeighborhood')
            """))
            print("❌ ERROR: Invalid reference was accepted (this shouldn't happen!)")
            
        except Exception:
            print("✅ Foreign key constraint correctly rejected invalid neighborhood reference")
        
        # Test 3: Try to delete a referenced district (should fail due to RESTRICT)
        try:
            test_district = conn.execute(text("""
                SELECT district FROM districts LIMIT 1
            """)).scalar()
            
            conn.execute(text("""
                DELETE FROM districts WHERE district = :district
            """), {'district': test_district})
            print("❌ ERROR: Referenced district was deleted (this shouldn't happen!)")
            
        except Exception:
            print("✅ ON DELETE RESTRICT correctly prevented deletion of referenced district")
        
        print("\n🎉 VALIDATION COMPLETE!")
        print("=" * 30)
        print("✅ Your foundation tables are ready for collaborative use!")
        print("✅ Other students can now safely reference your districts and neighborhoods!")
        print("✅ Data integrity is protected by foreign key constraints!")
        
except Exception as e:
    print(f"❌ Validation error: {e}")
    raise

🔍 Starting comprehensive validation...

📊 1. BASIC DATA VALIDATION
✅ Districts inserted: 12/12 expected
✅ Neighborhoods inserted: 96/~190 expected

🔗 2. FOREIGN KEY RELATIONSHIP VALIDATION
✅ Orphaned neighborhoods (should be 0): 0
📋 Districts and their neighborhood counts:
   🏛️ Charlottenburg-Wilmersdorf: 7 neighborhoods
   🏛️ Friedrichshain-Kreuzberg: 2 neighborhoods
   🏛️ Lichtenberg: 10 neighborhoods
   🏛️ Marzahn-Hellersdorf: 5 neighborhoods
   🏛️ Mitte: 6 neighborhoods
   🏛️ Neukölln: 5 neighborhoods
   🏛️ Pankow: 13 neighborhoods
   🏛️ Reinickendorf: 11 neighborhoods
   🏛️ Spandau: 9 neighborhoods
   🏛️ Steglitz-Zehlendorf: 7 neighborhoods
   🏛️ Tempelhof-Schöneberg: 6 neighborhoods
   🏛️ Treptow-Köpenick: 15 neighborhoods

🗺️ 3. SPATIAL DATA VALIDATION
✅ Invalid district geometries: 0
✅ Invalid neighborhood geometries: 0
📍 Spatial extents (Berlin should be ~13.0-13.8°E, 52.3-52.7°N):
   Districts: Lon(13.088 to 13.761), Lat(52.338 to 52.676)
   Neighborhoods: Lon(13.088 to 13.7

## 🎯 Mission Accomplished: Foundation Tables Created!

### 🏆 **What You've Achieved**
Congratulations! You've successfully created the **foundational layer** of our collaborative Berlin database. Your work now enables the entire team to build upon a solid, well-structured foundation.

### 📊 **Your Contribution Summary**
- ✅ **Data Processing**: Cleaned and prepared Berlin districts and neighborhoods data
- ✅ **Database Schema**: Created tables with proper spatial support and referential integrity  
- ✅ **Data Population**: Inserted 12 districts and ~190 neighborhoods with PostGIS geometries
- ✅ **Quality Assurance**: Validated data integrity and collaborative compatibility

### 🤝 **How Your Work Supports the Team**
Based on our **shared ERD**, your tables now serve as reference points for:

| Student Project | References Your Tables |
|----------------|----------------------|
| 🏫 **Schools Data** | `neighborhoods` table |
| 🏥 **Hospitals** | `neighborhoods` table |
| 🚌 **Public Transport** | `neighborhoods` table |
| 💰 **Land Prices** | `neighborhoods` table |
| 🏡 **Rental Statistics** | `districts` & `neighborhoods` |
| 📊 **Crime Data** | `neighborhoods` table |
| 🌳 **Green Spaces** | `districts` table |

### 🔄 **Next Steps for the Collaborative Project**
1. **Team Coordination**: Share your database connection details with other students
2. **Data Integration**: Other students can now reference your `district` and `neighborhood` values
3. **Advanced Queries**: Once all data is loaded, the team can perform cross-dataset analysis
4. **Quality Monitoring**: Your `ON DELETE RESTRICT` constraints protect data integrity

### 💡 **Key Learning Outcomes**
- **Spatial Databases**: Working with PostGIS and geometric data
- **Database Design**: Foreign keys, referential integrity, and collaborative schemas  
- **Data Pipeline**: ETL processes for real-world geographic data
- **Team Development**: Building foundational infrastructure for collaborative projects

**Well done! Your careful work ensures the entire team can build upon a robust, reliable foundation! 🚀**