{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e03c039e",
   "metadata": {},
   "source": [
    "Setup and Loading Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "e7a54c2e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shape before transformation: (423, 4)\n",
      "Columns before transformation: ['stop_id', 'stop_name', 'stop_lat', 'stop_lon']\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>stop_id</th>\n",
       "      <th>stop_name</th>\n",
       "      <th>stop_lat</th>\n",
       "      <th>stop_lon</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>de:12065:900200008:1:50</td>\n",
       "      <td>S Birkenwerder Bhf</td>\n",
       "      <td>52.688665</td>\n",
       "      <td>13.288775</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>de:12065:900200008:1:51</td>\n",
       "      <td>S Birkenwerder Bhf</td>\n",
       "      <td>52.688658</td>\n",
       "      <td>13.288626</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>de:11000:900001201:1:50</td>\n",
       "      <td>S+U Westhafen (Berlin)</td>\n",
       "      <td>52.536218</td>\n",
       "      <td>13.344329</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   stop_id               stop_name   stop_lat   stop_lon\n",
       "0  de:12065:900200008:1:50      S Birkenwerder Bhf  52.688665  13.288775\n",
       "1  de:12065:900200008:1:51      S Birkenwerder Bhf  52.688658  13.288626\n",
       "2  de:11000:900001201:1:50  S+U Westhafen (Berlin)  52.536218  13.344329"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "csv_path = \"/Users/hebifou/Downloads/GTFS/sbahn_stations_clean.csv\"\n",
    "\n",
    "df = pd.read_csv(csv_path)\n",
    "\n",
    "#data check\n",
    "print(\"Shape before transformation:\", df.shape)\n",
    "print(\"Columns before transformation:\", df.columns.tolist())\n",
    "display(df.head(3))  # preview first 3 rows\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f930ba79",
   "metadata": {},
   "source": [
    "Rename columns to match `ubahn` schema"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "ef0dc838",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shape after renaming/reordering: (423, 7)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>station</th>\n",
       "      <th>line</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>postcode</th>\n",
       "      <th>neighborhood</th>\n",
       "      <th>fkdistrict</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>S Birkenwerder Bhf</td>\n",
       "      <td>None</td>\n",
       "      <td>52.688665</td>\n",
       "      <td>13.288775</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>S Birkenwerder Bhf</td>\n",
       "      <td>None</td>\n",
       "      <td>52.688658</td>\n",
       "      <td>13.288626</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>S+U Westhafen (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.536218</td>\n",
       "      <td>13.344329</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                  station  line   latitude  longitude postcode neighborhood  \\\n",
       "0      S Birkenwerder Bhf  None  52.688665  13.288775     None         None   \n",
       "1      S Birkenwerder Bhf  None  52.688658  13.288626     None         None   \n",
       "2  S+U Westhafen (Berlin)  None  52.536218  13.344329     None         None   \n",
       "\n",
       "  fkdistrict  \n",
       "0       None  \n",
       "1       None  \n",
       "2       None  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "df = df.rename(columns={\n",
    "    \"stop_name\": \"station\",\n",
    "    \"stop_lat\": \"latitude\",\n",
    "    \"stop_lon\": \"longitude\"\n",
    "})\n",
    "\n",
    "#adding placeholder columns\n",
    "df[\"line\"] = None\n",
    "df[\"postcode\"] = None\n",
    "df[\"neighborhood\"] = None\n",
    "df[\"fkdistrict\"] = None\n",
    "\n",
    "#reordering columns\n",
    "df = df[[\"station\", \"line\", \"latitude\", \"longitude\", \"postcode\", \"neighborhood\", \"fkdistrict\"]]\n",
    "print(\"Shape after renaming/reordering:\", df.shape)\n",
    "display(df.head(3))  #checking first 3 rows after transformation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5eef426f",
   "metadata": {},
   "source": [
    "Data Quality Check"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "c185dd16",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Invalid coordinates found: 0\n"
     ]
    }
   ],
   "source": [
    "#checking for invalid coordinates \n",
    "invalid_coords = df[\n",
    "    (df[\"latitude\"] < 52.3) | (df[\"latitude\"] > 52.7) |\n",
    "    (df[\"longitude\"] < 13.0) | (df[\"longitude\"] > 13.8)\n",
    "]\n",
    "print(f\"Invalid coordinates found: {len(invalid_coords)}\")\n",
    "if not invalid_coords.empty:\n",
    "    display(invalid_coords)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "id": "d78a82c3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== Summary ===\n",
      "Total stations: 423\n",
      "Unique station names: 201\n"
     ]
    }
   ],
   "source": [
    "#summarizing stats\n",
    "print(\"\\n=== Summary ===\")\n",
    "print(\"Total stations:\", df.shape[0])\n",
    "print(\"Unique station names:\", df['station'].nunique())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "8b46156b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Duplicate station names found: 367\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>station</th>\n",
       "      <th>line</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>postcode</th>\n",
       "      <th>neighborhood</th>\n",
       "      <th>fkdistrict</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>412</th>\n",
       "      <td>Flughafen BER</td>\n",
       "      <td>None</td>\n",
       "      <td>52.364331</td>\n",
       "      <td>13.508164</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>411</th>\n",
       "      <td>Flughafen BER</td>\n",
       "      <td>None</td>\n",
       "      <td>52.364226</td>\n",
       "      <td>13.508213</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>194</th>\n",
       "      <td>S Adlershof (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.434867</td>\n",
       "      <td>13.541224</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>195</th>\n",
       "      <td>S Adlershof (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.434946</td>\n",
       "      <td>13.541382</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>153</th>\n",
       "      <td>S Ahrensfelde Bhf (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.571320</td>\n",
       "      <td>13.565711</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>305</th>\n",
       "      <td>S+U Yorckstr. (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.491334</td>\n",
       "      <td>13.372158</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>273</th>\n",
       "      <td>S+U Yorckstr. (Großgörschenstr.) (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.492301</td>\n",
       "      <td>13.367777</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>274</th>\n",
       "      <td>S+U Yorckstr. (Großgörschenstr.) (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.492245</td>\n",
       "      <td>13.367968</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>S+U Zoologischer Garten Bhf (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.507031</td>\n",
       "      <td>13.331849</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>S+U Zoologischer Garten Bhf (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.507068</td>\n",
       "      <td>13.331736</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>367 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                       station  line   latitude  longitude  \\\n",
       "412                              Flughafen BER  None  52.364331  13.508164   \n",
       "411                              Flughafen BER  None  52.364226  13.508213   \n",
       "194                       S Adlershof (Berlin)  None  52.434867  13.541224   \n",
       "195                       S Adlershof (Berlin)  None  52.434946  13.541382   \n",
       "153                 S Ahrensfelde Bhf (Berlin)  None  52.571320  13.565711   \n",
       "..                                         ...   ...        ...        ...   \n",
       "305                     S+U Yorckstr. (Berlin)  None  52.491334  13.372158   \n",
       "273  S+U Yorckstr. (Großgörschenstr.) (Berlin)  None  52.492301  13.367777   \n",
       "274  S+U Yorckstr. (Großgörschenstr.) (Berlin)  None  52.492245  13.367968   \n",
       "20        S+U Zoologischer Garten Bhf (Berlin)  None  52.507031  13.331849   \n",
       "21        S+U Zoologischer Garten Bhf (Berlin)  None  52.507068  13.331736   \n",
       "\n",
       "    postcode neighborhood fkdistrict  \n",
       "412     None         None       None  \n",
       "411     None         None       None  \n",
       "194     None         None       None  \n",
       "195     None         None       None  \n",
       "153     None         None       None  \n",
       "..       ...          ...        ...  \n",
       "305     None         None       None  \n",
       "273     None         None       None  \n",
       "274     None         None       None  \n",
       "20      None         None       None  \n",
       "21      None         None       None  \n",
       "\n",
       "[367 rows x 7 columns]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#checking duplicate station names\n",
    "duplicate_stations = df[df.duplicated(subset=[\"station\"], keep=False)]\n",
    "print(f\"Duplicate station names found: {len(duplicate_stations)}\")\n",
    "if not duplicate_stations.empty:\n",
    "    display(duplicate_stations.sort_values(\"station\"))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "18c299e0",
   "metadata": {},
   "source": [
    "Save transformed dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "87fe6ba3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "S-Bahn stations transformed and saved to sources/sbahn_stations_transformed.csv\n"
     ]
    }
   ],
   "source": [
    "output_dir = \"/Users/hebifou/Downloads/GTFS/sources\"\n",
    "os.makedirs(output_dir, exist_ok=True)\n",
    "\n",
    "df.to_csv(\"/Users/hebifou/Downloads/GTFS/sources/sbahn_stations_transformed.csv\", index=False)\n",
    "print(\"S-Bahn stations transformed and saved to sources/sbahn_stations_transformed.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "id": "688d7314",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== Final DataFrame Info ===\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 423 entries, 0 to 422\n",
      "Data columns (total 7 columns):\n",
      " #   Column        Non-Null Count  Dtype  \n",
      "---  ------        --------------  -----  \n",
      " 0   station       423 non-null    object \n",
      " 1   line          0 non-null      object \n",
      " 2   latitude      423 non-null    float64\n",
      " 3   longitude     423 non-null    float64\n",
      " 4   postcode      0 non-null      object \n",
      " 5   neighborhood  0 non-null      object \n",
      " 6   fkdistrict    0 non-null      object \n",
      "dtypes: float64(2), object(5)\n",
      "memory usage: 23.3+ KB\n",
      "None\n",
      "\n",
      "Columns: ['station', 'line', 'latitude', 'longitude', 'postcode', 'neighborhood', 'fkdistrict']\n",
      "\n",
      "=== First 5 rows ===\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>station</th>\n",
       "      <th>line</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>postcode</th>\n",
       "      <th>neighborhood</th>\n",
       "      <th>fkdistrict</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>S Birkenwerder Bhf</td>\n",
       "      <td>None</td>\n",
       "      <td>52.688665</td>\n",
       "      <td>13.288775</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>S Birkenwerder Bhf</td>\n",
       "      <td>None</td>\n",
       "      <td>52.688658</td>\n",
       "      <td>13.288626</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>S+U Westhafen (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.536218</td>\n",
       "      <td>13.344329</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>S+U Westhafen (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.536318</td>\n",
       "      <td>13.344298</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>S Bellevue (Berlin)</td>\n",
       "      <td>None</td>\n",
       "      <td>52.519946</td>\n",
       "      <td>13.348090</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                  station  line   latitude  longitude postcode neighborhood  \\\n",
       "0      S Birkenwerder Bhf  None  52.688665  13.288775     None         None   \n",
       "1      S Birkenwerder Bhf  None  52.688658  13.288626     None         None   \n",
       "2  S+U Westhafen (Berlin)  None  52.536218  13.344329     None         None   \n",
       "3  S+U Westhafen (Berlin)  None  52.536318  13.344298     None         None   \n",
       "4     S Bellevue (Berlin)  None  52.519946  13.348090     None         None   \n",
       "\n",
       "  fkdistrict  \n",
       "0       None  \n",
       "1       None  \n",
       "2       None  \n",
       "3       None  \n",
       "4       None  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== Summary ===\n",
      "Total stations: 423\n",
      "Unique station names: 201\n"
     ]
    }
   ],
   "source": [
    "print(\"=== Final DataFrame Info ===\")\n",
    "print(df.info())   # check column types and nulls\n",
    "print(\"\\nColumns:\", df.columns.tolist())\n",
    "\n",
    "print(\"\\n=== First 5 rows ===\")\n",
    "display(df.head())\n",
    "\n",
    "print(\"\\n=== Summary ===\")\n",
    "print(\"Total stations:\", df.shape[0])\n",
    "print(\"Unique station names:\", df['station'].nunique())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "3.10.13",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
